### PR TITLE
Update to Lucene 9.0.0

### PR DESCRIPTION
**Pull request by dainiusjocas**
Lucene 9.0.0 was just released with several breaking [changes](https://lucene.apache.org/core/9_0_0/changes/Changes.html).

Changes for the quarkus-lucene:
- remove `RAMDirectory`
- remove `SimpleFSDirectory`
- rename `lucene-analyzers-common` to `lucene-analysis-common`
- rename  `org.apache.lucene.analysis.util.CharFilterFactory` to `org.apache.lucene.analysis.CharFilterFactory`

### CODE REVIEW

**Comment by dainiusjocas** [comment]
> We need someone to maintain this extension as the original lead is unreachable and even deleted his github account. Would you be interested in leading this?

I would be interested. What would be the next steps?

**Comment by gastaldi** [comment]
@dainiusjocas I added you as the lead maintainer (you should receive an email soon).

Take a look at https://github.com/quarkiverse/quarkiverse/wiki/Checklist#when-your-extension-is-ready on how to perform a release when the extension is ready

**Comment by gastaldi** [comment]
@all-contributors add @dainiusjocas for code and maintenance

**Comment by dainiusjocas** [comment]
> Any objections about renaming the branch to `main`?

All good 👍

**Pull request closed without merging**
