### PR TITLE
Update to Quarkus 3

### PR DESCRIPTION
**Pull request by gsmet**
Hey there,

Here is a PR to update to Quarkus 3.

It would be nice if you could merge it and release a new major version (`1.0.0` ?) before April 25th so that it's ready for the announcement.

Please ping me when the release is done so that I can include it in our automatic update recipes.

Thanks!

### CODE REVIEW

**Comment by melloware** [comment]
@gsmet yep we will!

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@all-contributors add @gsmet for code

**Comment by melloware** [comment]
@dainiusjocas are you looking at this one?

**Review by dainiusjocas — APPROVED** [review]
Just a dependency bump.

**Pull request merged**
